"""Brochure content, adapted as editorial sections. Originals remain downloadable."""
from pathlib import Path
import struct
from turtle_art import turtle_art

def photo(name,alt,caption='',cls=''):
    # Consistent aspect ratios reserve layout before lazy image loading.
    return f'<figure class="editorial-photo {cls}"><img src="assets/brochure/{name}.webp" alt="{alt}" loading="lazy" width="900" height="700">'+(f'<figcaption>{caption}</figcaption>' if caption else '')+'</figure>'

def heading(kicker,title,id):
    return f'<div class="editorial-head"><p class="eyebrow">{kicker}</p><h2 class="display small" id="{id}" data-lines>{title}</h2></div>'

def gallery(items,cls=''):
    return '<div class="brochure-gallery '+cls+'" data-stagger>'+''.join(photo(name,label,label) for name,label in items)+'</div>'

BUBBLE = '''<section class="block bubble-study material-experience" id="pluriball" aria-labelledby="bubble-title">
<div class="wrap"><div class="study-heading"><div><p class="eyebrow">PLURIBALL / IL DETTAGLIO</p><h2 class="display small" id="bubble-title" data-lines>L’aria diventa<br><em>protezione.</em></h2></div><p>Una superficie leggera.<br>Una trama di piccole camere d’aria.</p></div>
<div class="bubble-window"><img class="bubble-photo" src="assets/bubble.webp" width="1500" height="1000" alt="Macro fotografica delle bolle del pluriball" loading="lazy"><div class="bubble-fold" aria-hidden="true"></div><div class="bubble-light" aria-hidden="true"></div><span class="bubble-caption">Pluriball · dettaglio del materiale</span></div>
<div class="bubble-tools"><span>Leggero. Flessibile. Protettivo.</span><button class="motion-replay" type="button" data-replay-material>Rivedi il movimento ↻</button></div>
<p class="lead">Il film a bolle d’aria avvolge gli oggetti e crea uno strato di protezione durante la movimentazione. Per superfici sensibili e lavorazioni su misura, la gamma prosegue con il polietilene espanso.</p></div></section>'''

FOAM = '<section class="block editorial-dark" id="foam" aria-labelledby="foam-title"><div class="wrap">'+heading('POLIETILENE ESPANSO','Leggero sulla materia.<br><em>Attento ai dettagli.</em>','foam-title')+'''<div class="editorial-split"><div><p class="lead">Il foam è un polietilene espanso: flessibile e modellabile, si adatta a profili, superfici e oggetti. La sua struttura accompagna il prodotto nella movimentazione e nella protezione quotidiana.</p><p class="lead">La brochure lo presenta per la protezione antigraffio di mobili, vetro e ceramica, con caratteristiche di leggerezza, maneggevolezza, resistenza allo strappo e recupero della forma.</p><div class="material-properties" data-stagger><span>Flessibile</span><span>Non abrasivo</span><span>Leggero</span><span>Protettivo</span></div></div>'''+photo('foam-protezione-lampada','Lampada protetta dal foam, fotografia della brochure','La protezione segue la forma.','portrait-photo')+'''</div>'''+gallery([('foam-bicchiere-cristallo','Vetro e cristallo'),('foam-ceramica-protetta','Superfici delicate'),('foam-sfera-protetta','Forme da avvolgere'),('foam-struttura-impermeabilita','La struttura del materiale')])+'''<div class="material-note"><h3>Una materia versatile.</h3><p>La brochure descrive un materiale impermeabile, resistente agli sbalzi di temperatura e capace di assorbire e dissipare urti. La scelta di densità, spessore e lavorazione dipende dall’applicazione.</p></div></div></section>'''

CUSTOM_FOAM = '<section class="block tinted" aria-labelledby="custom-foam"><div class="wrap">'+heading('FORME, SPESSORI, ACCOPPIAMENTI','La protezione giusta<br>ha la <em>tua forma.</em>','custom-foam')+'''<div class="editorial-split"><p class="lead">Formati e dimensioni diversi, fino alla realizzazione di una fustella dedicata. Il foam può essere accoppiato con altri materiali per rispondere a esigenze differenti di protezione e confezionamento.</p><div class="material-list"><span>Polietilene a bassa e alta densità</span><span>Film metallizzati</span><span>Carta</span><span>Pellicole adesive</span><span>Film a bolle d’aria</span></div></div>'''+gallery([('foam-piatti','Piatti e ceramiche'),('foam-profilo-mobile','Profili per l’arredo'),('foam-dettaglio-ceramica','Dettagli da preservare'),('foam-serramento','Serramenti e profili'),('foam-pallone','Oggetti sagomati'),('foam-tessuto-protettivo','Fogli protettivi'),('foam-piatto-ceramica','Protezione delle superfici')])+'''</div></section>'''

XTRACELL = '<section class="block" aria-labelledby="xtracell-title"><div class="wrap">'+heading('FOAM / XTRACELL','Assorbire.<br>Riprendere <em>forma.</em>','xtracell-title')+'''<div class="editorial-split"><div><p class="lead">Xtracell è presentato nella brochure come un polietilene espanso ad alto spessore, per imballaggi protettivi e riempimento. Una struttura pensata per accompagnare gli urti e contribuire alla stabilità del contenuto.</p><div class="material-properties"><span>Resilienza</span><span>Protezione antigraffio</span><span>Resistenza alla trazione</span><span>Riempimento</span></div><p class="lead">La scheda ne evidenzia anche la maneggevolezza e la leggerezza, insieme alla resistenza allo strappo e all’abrasione.</p></div>'''+photo('xtracell-ceramica','Ceramica appoggiata al foam Xtracell','Xtracell, dalla brochure aziendale.')+'''</div><div class="compression-story reveal"><div>'''+photo('xtracell-struttura','Struttura ondulata del foam Xtracell')+'''</div><div><h3>La differenza è nella risposta.</h3><p>Gli schemi della brochure illustrano il recupero della forma dopo la compressione e lo confrontano con il comportamento delle bolle d’aria.</p>'''+photo('xtracell-diagramma-compressione','Schema illustrativo di compressione e recupero del foam Xtracell','Xtracell · schema della brochure')+photo('bolle-aria-diagramma-compressione','Schema illustrativo di compressione di un materiale a bolle','Bolle d’aria · confronto illustrativo')+'''<p class="source-note">Gli schemi illustrano il comportamento descritto, senza sostituire una prova tecnica sulla specifica applicazione.</p></div></div></div></section>'''

ZERO = '<section class="block editorial-dark" aria-labelledby="zero-title"><div class="wrap">'+heading('FOAM / ZEROVIRGOLACINQUE','Mezzo millimetro.<br><em>Un’altra possibilità.</em>','zero-title')+'''<div class="editorial-split"><div><div class="large-measure">0,5<span>mm</span></div><p class="lead">Zerovirgolacinque è la proposta di foam a spessore ridotto descritta nella brochure. Nasce dall’impiego di materie prime rigenerate e punta a unire protezione, scorrevolezza e minore ingombro del rotolo.</p><p class="lead">A parità di volume, uno spessore minore permette di avvolgere più materiale: un tema che interessa stoccaggio, movimentazione e logistica.</p></div>'''+photo('zerovirgolacinque-bottiglia','Bottiglia protetta dal foam Zerovirgolacinque','Sottile, per avvolgere il prodotto.')+'''</div><div class="zero-detail">'''+photo('zerovirgolacinque-bicchiere','Bicchiere rivestito con foam Zerovirgolacinque')+'''<div><h3>Materia rigenerata.</h3><p>La brochure indica che il contenuto riciclato può arrivare fino al 100%. È una possibilità descritta per la linea, da verificare nella specifica composizione del prodotto richiesto.</p></div></div>
<details class="technical-data"><summary>Dentro i dati della brochure <span aria-hidden="true">+</span></summary><div class="table-scroll" role="region" aria-label="Dati comparativi Zerovirgolacinque" tabindex="0"><table><caption>Confronto riportato nella brochure FOAM, pagina 9</caption><thead><tr><th>Caratteristica</th><th>PE 1 mm</th><th>PE 0,5 mm simulato</th><th>Zerovirgolacinque</th></tr></thead><tbody><tr><th>Compressione al 25% (kPa)</th><td>10,6</td><td>5,3</td><td>21,2</td></tr><tr><th>Trazione longitudinale*</th><td>9,3</td><td>4,65</td><td>7,9</td></tr><tr><th>Trazione trasversale*</th><td>3,4</td><td>1,7</td><td>2,9</td></tr></tbody></table></div><p class="source-note">La brochure riporta +300% in compressione, +69,9% e +70,6% in trazione rispetto al PE di 0,5 mm <strong>simulato matematicamente</strong>, non rispetto al PE di 1 mm. *Le unità della trazione non sono indicate nella tabella originale. Dati della brochure, da verificare sulla specifica fornitura.</p></details></div></section>'''

APPLICATIONS = '<section class="block" aria-labelledby="applications-title"><div class="wrap">'+heading('IL FOAM NELLA VITA DI OGNI GIORNO','Una materia.<br><em>Molte applicazioni.</em>','applications-title')+'''<p class="lead">Dall’isolamento di frigoriferi e congelatori alle imbottiture di mobili, materassi e tappeti. Dai componenti per automobili alle suole delle scarpe e all’abbigliamento sportivo: la brochure racconta la versatilità del materiale.</p><p class="lead">Le applicazioni comprendono anche i settori medico e farmaceutico, edile, manifatturiero, artigianale, tessile, elettronico ed energetico.</p>'''+gallery([('applicazione-acustica','Acustica'),('applicazione-arredamento','Arredamento'),('applicazione-automotive','Automotive'),('applicazione-edilizia','Edilizia'),('applicazione-fitness','Fitness'),('applicazione-giocattoli','Giochi'),('applicazione-gioielli','Oggetti preziosi'),('applicazione-logistica','Logistica'),('applicazione-meccanica','Meccanica'),('applicazione-nautica','Nautica'),('applicazione-protezione-sport','Protezioni sportive'),('applicazione-utensili','Utensili')],'application-gallery')+'''<a class="text-link" href="assets/brochure-foam.pdf" target="_blank" rel="noopener">Sfoglia la brochure completa <span>↗</span></a></div></section>'''

ECO = '''<section class="block eco-story editorial-dark" aria-labelledby="eco-story-title"><div class="wrap"><div class="editorial-head"><p class="eyebrow">UN GESTO, UNA DIREZIONE</p><h2 class="display small" id="eco-story-title" data-lines>Lasciare spazio<br><em>alla vita.</em></h2></div><div class="eco-window"><img class="eco-world" src="assets/turtle-ocean-v17.png" width="1536" height="1024" alt="Visione evocativa di una tartaruga marina in acque verdi, immagine generata" loading="lazy"><div class="eco-cloud" aria-hidden="true"></div><div class="eco-sweep" aria-hidden="true"></div><span class="eco-traveller">'''+turtle_art("eco")+'''</span></div><div class="eco-caption"><p>La tartaruga ci accompagna verso un uso più consapevole della materia.</p><button class="motion-replay" type="button">Rivedi il movimento ↻</button></div></div></section>'''

CIRCULAR = '<section class="block" aria-labelledby="circular-title"><div class="wrap">'+heading('ECO-INNOVAZIONE','Il valore non finisce<br><em>al primo utilizzo.</em>','circular-title')+'''<div class="editorial-split"><div><p class="lead">Dalla seconda metà dell’Ottocento, la plastica ha trasformato molti settori produttivi. Oggi la sfida raccontata nelle brochure è ripensare il packaging attraverso ricerca, innovazione ed ecodesign.</p><p class="lead">All’approccio lineare — estrarre, produrre, gettare — si affianca un modello che considera l’uso delle risorse e il recupero dei materiali già in fase di progetto.</p><div class="cycle-steps" data-stagger><div><span>01</span><h3>Produrre</h3><p>Considerare materiali e funzione.</p></div><div><span>02</span><h3>Utilizzare</h3><p>Proteggere durante il percorso.</p></div><div><span>03</span><h3>Riciclare</h3><p>Restituire valore alla materia.</p></div></div></div>'''+photo('economia-circolare-mano','La circolarità illustrata nella presentazione Imballaggi 2G')+'''</div><div class="eco-pair">'''+photo('economia-lineare-circolare','Confronto fra economia lineare e circolare','Il modello illustrato nella presentazione.')+photo('eco-innovazione-bottiglia','Immagine verde di una bottiglia, dalla brochure sull’eco-innovazione','Ricerca, materia, nuove possibilità.')+'''</div></div></section>'''

PSV = '<section class="block tinted" aria-labelledby="psv-meaning"><div class="wrap">'+heading('PLASTICA SECONDA VITA','Una filiera da conoscere.<br>Un contenuto da <em>tracciare.</em>','psv-meaning')+'''<div class="editorial-split"><div><p class="lead">Plastica Seconda Vita identifica prodotti ottenuti con materiale riciclato e ne rende riconoscibili origine e contenuto, nell’ambito del rispettivo schema di certificazione.</p><p class="lead">La presentazione descrive la tracciabilità, il calcolo del contenuto riciclato e la verifica indipendente. Richiama UNI UNIPLAST 10667, EN 15343 e UNI EN ISO 14021.</p></div><div><h3>Il ruolo di IPPR</h3><p class="lead">L’Istituto per la Promozione delle Plastiche da Riciclo, costituito da Unionplast, PlasticsEurope Italia e Corepla, mette in relazione domanda e offerta di prodotti riciclati e promuove la loro riconoscibilità, anche attraverso il repertorio dei prodotti.</p></div></div><div class="audience-grid" data-stagger><article><span>01</span><h3>Imprese</h3><p>Qualificare materiali e prodotti.</p></article><article><span>02</span><h3>Enti pubblici</h3><p>Individuare soluzioni per gli acquisti verdi.</p></article><article><span>03</span><h3>Persone</h3><p>Riconoscere il contenuto riciclato.</p></article><article><span>04</span><h3>Distribuzione</h3><p>Rispondere all’attenzione ambientale dei clienti.</p></article></div></div></section>'''

CAM = '<section class="block" aria-labelledby="cam-title"><div class="wrap">'+heading('ACQUISTI E AMBIENTE','Scegliere considerando<br><em>l’intero percorso.</em>','cam-title')+'''<div class="editorial-split"><div><h3>CAM e acquisti verdi</h3><p class="lead">I Criteri Ambientali Minimi considerano gli aspetti ambientali nelle diverse fasi di un acquisto. La presentazione li collega al Green Public Procurement: l’attenzione all’ambiente negli acquisti delle pubbliche amministrazioni.</p><p class="lead">Il tema va oltre il singolo materiale: progettazione, produzione, utilizzo, recupero e logistica concorrono a un approccio più circolare, con ricadute sulle filiere e sul territorio.</p><p class="source-note">La documentazione richiesta dipende dal prodotto e dalla specifica procedura di acquisto. La certificazione PSV non equivale da sola alla conformità a ogni criterio CAM.</p></div><div class="cam-art">'''+photo('ambiente-energia-risorse','Illustrazione su ambiente, energia e risorse dalla presentazione')+photo('cam-marchio','Simbolo dei Criteri Ambientali Minimi presente nella brochure')+'''</div></div></div></section>'''

CARBON = '<section class="block tinted" aria-labelledby="carbon-title"><div class="wrap">'+heading('GREEN CARBON FOOTPRINT','Misurare l’impatto.<br><em>Per migliorarlo.</em>','carbon-title')+'''<div class="editorial-split"><div class="carbon-measure">CO<sub>2</sub><span>equivalente</span></div><div><p class="lead">L’impronta climatica esprime in CO₂ equivalente le emissioni di gas serra associate, direttamente e indirettamente, a un prodotto, un’organizzazione o un servizio.</p><p class="lead">La brochure richiama la UNI EN ISO 14067:2018 per l’impronta climatica dei prodotti e le norme ISO 14040 e 14044 per la valutazione del ciclo di vita, o LCA.</p><p class="lead">Ridurre spessore, ingombro e impiego di materia è un obiettivo progettuale. Quantificare il beneficio ambientale richiede una valutazione riferita al prodotto e al suo ciclo di vita.</p><a class="text-link" href="protezioni.html#zero-title">Scopri Zerovirgolacinque <span>↗</span></a></div></div></div></section>'''

PUGLIA = '<section class="block editorial-dark" aria-labelledby="puglia-title"><div class="wrap">'+heading('PUGLIA PLASTIC SECOND LIFE','Un territorio.<br><em>Una responsabilità condivisa.</em>','puglia-title')+'''<div class="editorial-split middle"><div><p class="lead">Nella presentazione, Imballaggi 2G dedica un riconoscimento ai clienti che scelgono prodotti Plastica Seconda Vita: un segno visibile dell’adesione al percorso promosso dall’azienda.</p><p class="lead">L’iniziativa propone una targa da esporre per creare una rete di realtà attente alla circolarità della materia.</p><p class="source-note">Puglia Plastic Second Life è il riconoscimento aziendale descritto nella presentazione, distinto dalla certificazione di prodotto rilasciata da IIP.</p></div><img class="puglia-lockup" src="assets/turtle-light.webp" width="1107" height="491" alt="Puglia Plastic Second Life, marchio dell’iniziativa aziendale" loading="lazy"></div></div></section>'''

BIODIVERSITY = '<section class="block" aria-labelledby="biodiversity-title"><div class="wrap">'+heading('LA BIODIVERSITÀ, UN PATRIMONIO COMUNE','Ogni vita è una parte<br><em>del nostro mondo.</em>','biodiversity-title')+'''<div class="editorial-split"><div><p class="lead">La presentazione usa l’immagine di un puzzle: ogni specie è un tassello di conoscenza, relazioni e diversità che non possiamo sostituire.</p><p class="lead">Sfruttamento delle risorse, cambiamenti del clima e inquinamento sono i temi richiamati nel racconto aziendale per invitare a una maggiore attenzione verso il mondo vivente.</p></div>'''+photo('biodiversita-mondo-puzzle','Il mondo come puzzle di elementi naturali','Tu fai parte di quel puzzle.','puzzle-photo')+'''</div>'''+gallery([('biodiversita-tartaruga','La vita nel mare'),('biodiversita-leopardo','La diversità dei grandi felini'),('biodiversita-orso','Gli ambienti terrestri'),('biodiversita-orango','La vita nelle foreste'),('biodiversita-tigre','I grandi predatori'),('biodiversita-gorilla','Gli equilibri delle foreste'),('biodiversita-cetaceo','Gli ecosistemi marini'),('biodiversita-mammifero-bosco','La fauna dei boschi'),('biodiversita-elefante','I grandi mammiferi'),('biodiversita-stambecco','La vita in montagna'),('biodiversita-farfalla','Le piccole forme di vita'),('biodiversita-rapace','La vita nell’aria')],'biodiversity-gallery')+'''<p class="source-note">Immagini e percorso tematico dalla presentazione Plastica Seconda Vita fornita dall’azienda.</p></div></section>'''

TIGER_MORE = '<section class="block" aria-labelledby="tiger-project"><div class="wrap">'+heading('IL PROGETTO TIGER FILM','Tre linee.<br><em>La stessa direzione.</em>','tiger-project')+'''<div class="editorial-split"><div><p class="lead">Tiger Film dà un’identità ai progetti sviluppati da Imballaggi 2G sul tema della sostenibilità. La presentazione coinvolge l’intera filiera nella costruzione di un’economia circolare per gli imballaggi flessibili.</p><p class="lead">Le tre linee del certificato MixEco impiegano polietilene con contenuto di riciclato. L’allegato indica dimensioni variabili e colori neutro, colorato trasparente o colorato coprente.</p></div><div class="material-list"><span>Eco Converting · PE-LD</span><span>Eco Manuale · PE-LLD estensibile</span><span>Eco Automatico · PE-LLD estensibile</span></div></div>'''+gallery([('tiger-film-bobine-verde','Film per il confezionamento'),('tiger-film-bobine','Formati in bobina'),('tiger-film-bobina','La pellicola distesa'),('tiger-film-manuale','Confezionamento manuale')])+'''<details class="technical-data"><summary>Consulta l’allegato prodotti <span>+</span></summary><div class="annex-view">'''+photo('certificato-psv-allegato-prodotti','Allegato originale al certificato PSV 3040/2024 con gamma, percentuali e spessori')+'''<div><h3>Dati riferiti alle linee certificate.</h3><p>L’allegato riporta il contenuto totale riciclato e lo spessore minimo di ogni linea. Non specifica la ripartizione tra riciclato pre-consumo e post-consumo; le percentuali non vengono quindi attribuite a una delle due origini.</p><a class="text-link" href="assets/presentazione-plastica-seconda-vita.pdf#page=9" target="_blank" rel="noopener">Apri l’originale <span>↗</span></a></div></div></details></div></section>'''

COMPANY_MORE = '<section class="block" aria-labelledby="family-title"><div class="wrap">'+heading('DALLA BROCHURE AZIENDALE','Le persone.<br><em>Prima di tutto.</em>','family-title')+'''<div class="editorial-split">'''+photo('famiglia-giuri-storia','Fotografia storica aziendale tratta dalla brochure Imballaggi 2G','Dall’archivio della brochure aziendale.','portrait-photo')+'''<div><p class="lead">Il percorso di Aldo Giuri passa da una prima attività a una seconda realtà dedicata alla produzione di materiale plastico. È su queste basi che si sviluppa una visione più ampia del packaging, portata avanti dalla seconda generazione.</p><p class="lead">Cura del dettaglio, investimenti nella tecnologia, formazione continua e flessibilità nella gestione sono i punti su cui la brochure costruisce l’identità di Imballaggi 2G.</p><blockquote>Guardare al futuro<br>e progredire.</blockquote><p class="lead">Una gamma pensata per bisogni professionali diversi: retailer della grande distribuzione, alberghi, ristoranti, aziende private ed enti pubblici.</p><a class="text-link" href="contatti.html">Conosciamoci <span>↗</span></a></div></div></div></section>'''

CERT_MORE = '''<section class="block tinted" aria-labelledby="cert-scope"><div class="wrap">'''+heading('LEGGERE I DOCUMENTI','Il valore è anche<br>nella <em>precisione.</em>','cert-scope')+'''<div class="certificate-facts"><article><span>3040 / 2024</span><h3>PSV MixEco</h3><p>Commercializzazione di film in polietilene certificato PSV MixEco. Marchio con numero distintivo 5718; verifica e sorveglianza IIP.</p><dl><dt>Prima emissione</dt><dd>4 marzo 2024</dd><dt>Scadenza indicata</dt><dd>3 marzo 2027</dd></dl><a href="assets/certificato-film-3040-2024.pdf" target="_blank" rel="noopener">Certificato originale ↗</a></article><article><span>3433 / 2026</span><h3>PSV Sottoprodotto</h3><p>Produzione di coprispalla, coprisedia, buste e fogli protettivi, mediante taglio e saldatura con MPS da sottoprodotto esterno.</p><dl><dt>Numero distintivo</dt><dd>5718</dd><dt>Scadenza indicata</dt><dd>9 giugno 2029</dd></dl><a href="assets/certificato-coprispalla-3433-2026.pdf" target="_blank" rel="noopener">Certificato originale ↗</a></article></div><p class="source-note">Le scadenze sono quelle riportate nei documenti, salvo modifica, sospensione o revoca. La certificazione riguarda i prodotti nel relativo campo di applicazione.</p><details class="technical-data"><summary>Visualizza il certificato MixEco nella presentazione <span>+</span></summary>'''+photo('certificato-psv-3040-2024','Riproduzione del certificato PSV MixEco della presentazione aziendale','Certificato incluso nella presentazione, pagina 8.','certificate-image')+'''</details></div></section>'''

EXTRA = {
    'protezioni': BUBBLE+FOAM+CUSTOM_FOAM+XTRACELL+ZERO+APPLICATIONS,
    'sostenibilita': ECO+CIRCULAR+PSV+CAM+CARBON+PUGLIA+BIODIVERSITY+CERT_MORE,
    'bobine': TIGER_MORE,
    'azienda': COMPANY_MORE,
}

def enrich(key, body):
    if key == 'protezioni':
        hero, remaining = body.split('</section>', 1)
        gama, ending = remaining.split('</section>', 1)
        return hero+'</section>'+BUBBLE+gama+'</section>'+FOAM+CUSTOM_FOAM+XTRACELL+ZERO+APPLICATIONS+ending
    if key == 'sostenibilita':
        hero, remaining = body.split('</section>', 1)
        cert = remaining[remaining.index('<section class="block" aria-labelledby="so-cert">'):]
        return hero+'</section>'+ECO+CIRCULAR+PSV+PUGLIA+CAM+CARBON+BIODIVERSITY+cert+CERT_MORE
    return body+EXTRA.get(key,'')
